### ISSUE TITLE
Parameter for number of background processes is ignored

### ISSUE THREAD

**Issue by martinhellwagner** [ostark/craft-async-queue#28] opened 2020-03-24 10:08 UTC
We're facing the problem that the parameter for the number of concurrent background processes – set in the environment file via `ASYNC_QUEUE_CONCURRENCY=4` – is ignored at times. First, everything seems fine and the maximum number of reserved processes equals the number set in the env file. However, after a while (hard to say when exactly, but it happens) the number of concurrent processes starts to increase, bringing the CPU close to 100% and endangering the uptime of the website. This is particularly worrying when there are a lot of processes to be dealt with. Restarting PHP helps solve the issue, but isn't a feasible solution.

In the screenshots below, you can see that there's a limit of 4 set in the plugin, but there are 7 concurrent processes. We're running **Craft 3.4.10.1** (latest as of today) with **PHP 7.2** on a Web Server with **Ubuntu 18.04**.

![Screenshot 2020-03-24 at 10 55 53](https://user-images.githubusercontent.com/19146752/77413536-cb95e180-6dbf-11ea-8194-f9b9fced18a1.png)

![Screenshot 2020-03-24 at 10 54 23](https://user-images.githubusercontent.com/19146752/77413546-ce90d200-6dbf-11ea-98bb-8f5fed0a7358.png)

**Comment by ostark** [comment] 2020-03-24 10:16
Servus @martinhellwagner!
It's probably related to https://github.com/ostark/craft-async-queue/issues/27 - the details you provided are useful. This could be a lead to solve it eventually.

**Comment by martinhellwagner** [comment] 2020-03-24 10:20
Grüß dich @ostark! 🙂 

Glad I could help! Let me know if you need further information. I'm monitoring the queue as we speak in order to find a pattern. 4 concurrent jobs keep the CPU at 60-70% according to our monitoring, while 6+ concurrent jobs drive it up to 90-100%.

**Comment by martinhellwagner** [comment] 2020-03-24 10:31
By the way, this is how the queue looks like when everything's still good (for example after a PHP restart):

![Screenshot 2020-03-24 at 11 30 11](https://user-images.githubusercontent.com/19146752/77415528-e7e74d80-6dc2-11ea-827f-9204f44bfa2c.png)

**Comment by ostark** [comment] 2020-03-24 10:38
Can you watch out for the message `Has not waited the lock.` in your queue/console/web logs?

**Comment by martinhellwagner** [comment] 2020-03-24 10:57
Strangely, we don't have a `queue.log` file in our currently deployed release on the Production system – only on the Stage system.

However, I've found two instances of this error in the `console.log` file on the Production system:

```
2020-03-23 19:39:19 [-][-][-][error][yii\base\Exception] yii\base\Exception: Has not waited the lock. in /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/craftcms/cms/src/queue/Queue.php:562
Stack trace:
#0 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/craftcms/cms/src/queue/Queue.php(120): craft\queue\Queue->reserve()
#1 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/craftcms/cms/src/queue/Command.php(77): craft\queue\Queue->run()
#2 [internal function]: craft\queue\Command->actionRun()
#3 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('run', Array)
#6 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('run', Array)
#7 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/run', Array)
#8 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('queue/run', Array)
#9 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/run', Array)
#10 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#11 /home/forge/www.bistum-passau.de/releases/165c676b83330391a42e7d3556134840dca5ce29/craft(23): yii\base\Application->run()
#12 {main}
2020-03-23 19:39:16 [-][-][-][info][application] $_GET = []
```

**Comment by martinhellwagner** [comment] 2020-03-24 11:22
What I've also noticed: when I'm restarting PHP, then I'm sometimes running into the same issue described in https://github.com/ostark/craft-async-queue/issues/27 – that the pending jobs aren't executed. I can force them to run via `./craft queue/run` in the Craft CLI though.

**Comment by martinhellwagner** [comment] 2020-03-24 12:35
If you don't restart PHP, the queue keeps adding more and more concurrent processes (currently 9):

![Screenshot 2020-03-24 at 13 34 38](https://user-images.githubusercontent.com/19146752/77426190-4b2dab80-6dd4-11ea-8c93-0ee3f2036334.png)

**Comment by ostark** [comment] 2020-03-24 12:38
It would be great to get the related logs:

1. Enable debugMode
2. `tail -f storage/logs/web.log | grep ProcessPool`

**Comment by martinhellwagner** [comment] 2020-03-24 12:47
There's an awful lot of output on the console for this command, since the queue has just finished running 40k jobs. Does it make sense to attach the log files as a ZIP here for your to look into?

**Comment by ostark** [comment] 2020-03-24 12:51
just 20 lines or so

**Comment by martinhellwagner** [comment] 2020-03-24 12:53
This is the latest Iogs I'm getting:

```
forge@bistum01:~/www.bistum-passau.de/current$ tail -f storage/logs/web.log | grep ProcessPool
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:00 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:01 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
tail: storage/logs/web.log: file truncated
2020-03-24 13:53:02 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][-][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][-][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][-][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:02 [-][12875][-][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Deleting stale template caches)
2020-03-24 13:53:04 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:04 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:04 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:04 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
2020-03-24 13:53:04 [-][12875][gfvr2kck6te0f0di3rm38n7ip3][trace][async-queue] ProcessPool::canIUse() (4 of 4, context: Updating search indexes)
```

**Comment by martinhellwagner** [comment] 2020-03-24 12:54
`devMode` is enabled

**Comment by martinhellwagner** [comment] 2020-03-24 12:55
Currently, we are back at 4 concurrent jobs after a PHP restart. I'll check and make sure to output some logs again when there are > 4 concurrent jobs.

**Comment by ostark** [comment] 2020-03-24 22:54
Can you try
```
composer require ostark/craft-async-queue:dev-reserved#cc91929d06111f145629f67d49730cb44b9d809d
```

**Comment by martinhellwagner** [comment] 2020-03-25 12:52
Just installed it and tried it out. The async queue test from _Utilities_ works fine, but there seems to be one job too many when looking at concurrent processes:

![Screenshot 2020-03-25 at 13 47 26](https://user-images.githubusercontent.com/19146752/77538275-c27c4180-6e9f-11ea-8a35-870c699b4d3f.png)

Just watched 600 jobs being executed, and it never exceeded 5 concurrent jobs though. It was either 4 or 5 jobs at a time.

**Comment by martinhellwagner** [comment] 2020-03-25 12:59
Update: now I can actually also reproduce 6 jobs being executed at the same time. I have installed the plugin from the `reserved` branch in this repo.

![Screenshot 2020-03-25 at 13 58 22](https://user-images.githubusercontent.com/19146752/77538902-c5c3fd00-6ea0-11ea-9c51-79625f7d33a2.png)

**Comment by martinhellwagner** [comment] 2020-03-25 13:50
Even though the async queue test works fine with the maximum number of concurrent jobs (still set at 4), the "normal" queue doesn't. I've triggered a queue of 4.000+ jobs and watched it being processed. Still 5+ jobs at a time:

![Screenshot 2020-03-25 at 14 49 41](https://user-images.githubusercontent.com/19146752/77543371-e2176800-6ea7-11ea-801a-ae69c5549364.png)

Am I missing something here?

**Comment by ostark** [comment] 2020-03-25 14:29
> I've triggered a queue of 5.000+ jobs 

Can you explain how you do it?

--
FYI: the Info table on the Test Utility is a bit misleading so far. I'll push an update later today.

**Comment by martinhellwagner** [comment] 2020-03-25 14:40
From the CP, I've rebuilt the asset indexes of one of our volumes, which contains 115 images. Since we have a lot of multisites on this particular project, this action triggered around 5.700 queue jobs – mostly "Update search indexes", as seen in the screenshot above.

**Comment by ostark** [comment] 2020-03-26 08:56
Honestly, I can't reproduce how you create that many processes (6 instead of 4) with the changes I made.
I release 2.1 https://github.com/ostark/craft-async-queue/commit/f53f835f446afa7dbb5af8d42b0482ba3fbafbce 

Closing this issue. Hopefully, the new release prevents real damage on your server.

**Closed by ostark** 2020-03-26 08:56 UTC

**Comment by martinhellwagner** [comment] 2020-03-26 09:01
Okay, I'll install the release and check again. Thanks for your help! 🙂

**Comment by martinhellwagner** [comment] 2020-03-27 07:32
For what it's worth, I could now reproduce the "Has not waited the lock" error in the Craft CLI (with version 2.0.0 on our Production system):

![Screenshot 2020-03-26 at 23 13 53](https://user-images.githubusercontent.com/19146752/77732590-70553080-7005-11ea-889d-adc8a7a3289a.png)

Will upgrade the Production system to version 2.1.0 though.

**Comment by ostark** [comment] 2020-03-27 08:52
Let me know if it makes a difference

**Comment by martinhellwagner** [comment] 2020-03-27 09:59
Unfortunately not. The same error still pops up in the CLI. In the Queue Manager – even though I increased the limit of concurrent jobs to 16 for testing purposes – I'm still getting weird numbers and behaviour.

![Screenshot 2020-03-27 at 10 56 37](https://user-images.githubusercontent.com/19146752/77744564-16ab3100-701a-11ea-8973-5b2eb3023011.png)

![Screenshot 2020-03-27 at 10 56 55](https://user-images.githubusercontent.com/19146752/77744570-1743c780-701a-11ea-8a5c-66848237cae4.png)

**Comment by ostark** [comment] 2020-03-27 10:20
When you set the max concurrency to 16, it is the upper limit of queue/run processes. 'Reserved' in the manager table and 'Reserverad Jobs' in the test utility should be the same, as the source is the same.

**Comment by martinhellwagner** [comment] 2020-03-27 10:40
Actually, we just discovered that since updating to 2.1.0, we're receiving multiple deadlock messages in our logs and trying to upload images:

![Screenshot 2020-03-27 at 11 38 31](https://user-images.githubusercontent.com/19146752/77747933-cc2cb300-701f-11ea-86f8-5ffd508aa567.png)

Have to revert back 2.0.0, it seems.

**Comment by martinhellwagner** [comment] 2020-03-27 10:44
Does the upper level mean that there can be less (but can't be more) concurrent jobs? Is is possible to tell the queue to use the exact number of concurrent processes – never less, never more?

**Comment by martinhellwagner** [comment] 2020-03-27 10:45
We need to find a trade-off between fast a queue while keeping server load to a good percentage.

**Comment by ostark** [comment] 2020-03-27 11:03
Sorry, that's beyond the scope of the plugin.  [ASYNC_QUEUE_CONCURRENCY](https://github.com/ostark/craft-async-queue#configuration-optional) should prevent damage, aka heavy load on the server.

I would not use the Craft's DB queue for high concurrency. Use SQS or Redis and run multiple `queue/listen`ers.
