### ISSUE TITLE
Error on Resaving Entries task

### ISSUE THREAD

**Issue by nfourtythree** [ostark/craft-async-queue#5] opened 2018-03-08 11:10 UTC
Having installed the plugin and setup the correct `PHP_BINARY` I am getting an error with the **Resaving Entries** task after editing an entry type field layout. Happens both locally and on a staging site.

The error in the queue DB table states `Calling unknown method: craft\console\Request::getIsPost()`.

When I re-run the task using the "Try again" option in the CP it works fine, which looks to go through the usual ajax task process.

Have you noticed anything like this already? Let me know if you need more info, logs etc.

Thanks!

**Comment by ostark** [comment] 2018-03-08 14:26
Good catch! This needs to be fixed in craft core.
I'll have a look if there is more like this and will open an issue or send a PR.

**Comment by nfourtythree** [comment] 2018-03-08 14:28
Yea it looked to me as an issue through the core, obviously just triggered via calling the tasks in this method.

Hopefully, it won't be too big of an issue to solve, as this plugin is great!

**Comment by ostark** [comment] 2018-03-08 14:37
@nfourtythree Thanks for your report!

**Comment by ostark** [comment] 2018-03-08 19:39
@nfourtythree 

Which version do you use
craftcms/cms
ostark/craft-async-queue
php
?

I can't reproduce this error so far. Can you provide `phperror.log` `queue.log` and `console.log` for that event?

Also, I can't find where `Request::getIsPost()` is called in when Resaving Entries.

**Comment by nfourtythree** [comment] 2018-03-09 14:04
@ostark Version details are as follows:

Craft: **3.0.0-RC13**
Async: **1.3.0**
PHP: **7.1 (staging)** / **7.0 (local)**

Zip of logs: http://x.n43.me/3R1F3M203o0n/Archive%202018-03-09%20at%202.03.17%20pm.zip

When I get a second I will check in relation to plugins, but there aren't too many installed. Thanks for looking into it!

**Comment by angrybrad** [comment] 2018-03-09 22:33
From the `queue.log` file stack trace, looks like it's originating from the Simple Map plugin you've got installed:

```
2018-03-08 11:04:57 [-][-][-][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: craft\console\Request::getIsPost() in /var/www/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /var/www/vendor/ether/simplemap/src/services/MapService.php(159): yii\base\Component->__call('getIsPost', Array)
#1 /var/www/vendor/ether/simplemap/src/fields/MapField.php(520): ether\simplemap\services\MapService->getField(Object(ether\simplemap\fields\MapField), Object(craft\elements\MatrixBlock), NULL)
#2 /var/www/vendor/craftcms/cms/src/base/Element.php(1803): ether\simplemap\fields\MapField->normalizeValue(NULL, Object(craft\elements\MatrixBlock))
#3 /var/www/vendor/craftcms/cms/src/base/Element.php(1483): craft\base\Element->normalizeFieldValue('map')
#4 /var/www/vendor/craftcms/cms/src/fields/Matrix.php(558): craft\base\Element->getFieldValue('map')
...
```

**Comment by nfourtythree** [comment] 2018-03-10 10:15
Good spot, hadn’t had a chance to go through the logs properly. 

Will have to look at a little pull request to the plugin to get it sorted. 

Thanks for the help peeps

**Comment by ostark** [comment] 2018-03-13 20:27
@nfourtythree https://github.com/ethercreative/simplemap/issues/96
Fixed!

**Closed** 2018-03-13 20:28 UTC
